import Login from "./Login";
import Signup from "./Signup";
import Welcome from "./Welcome";
import ForgotPassword from "./ForgotPassword";
import ChangePassword from "./ChangePassword";
import DashBoard from "./DashBoard";
import AddNewFine from "./AddNewFine";
import VehicleDetails from "./VehicleDetails";
import CheckS from "./CheckS";
import DriverFineHistory from "./DriverFIneHistory";
import Message from "./Message";
export { Login, Signup, Welcome, ForgotPassword, ChangePassword, DashBoard, AddNewFine, VehicleDetails ,DriverFineHistory,Message, CheckS};